version: '3'

services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8080:80"    # HTTP port for stats page
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stat.xsl:/usr/local/nginx/html/stat.xsl
      - ./player.html:/usr/local/nginx/html/player.html
    restart: unless-stopped
    
  player-app:
    build:
      context: ./player-app
      dockerfile: Dockerfile
    image: rtmp-player-app:latest
    volumes:
      - ./player-app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"  # Next.js app port
    depends_on:
      - rtmp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_RTMP_HOST=rtmp-server
      - NEXT_PUBLIC_RTMP_PORT=80 